"use client";
import { useEffect, useState } from "react";
import { readContract, writeContract } from "@/lib/genlayer";
import { requestAccounts } from "@/lib/wallet";
import type { Engagement, EvidenceKind, EvidenceRef } from "@/lib/types";
import { validateEvidenceRefs } from "@/lib/validation";
import { TransactionNotice } from "@/components/TransactionNotice";
const kinds: EvidenceKind[] = ["VERSIONED_SOURCE", "TRANSACTION", "PUBLIC_ARTIFACT", "LIVE_DEPLOYMENT"];
export default function SubmitPage({ params }: { params: Promise<{ engagementId: string }> }) {
  const [engagementId, setEngagementId] = useState(""); const [item, setItem] = useState<Engagement | null>(null); const [refs, setRefs] = useState<Record<number, EvidenceRef[]>>({}); const [hash, setHash] = useState(""); const [error, setError] = useState(""); const [canonical, setCanonical] = useState("");
  useEffect(() => { params.then(({ engagementId: id }) => { setEngagementId(id); requestAccounts().then((a) => readContract<Engagement>("get_engagement", [id], window.ethereum, a[0])).then(setItem).catch((e) => setError(e instanceof Error ? e.message : "Connect a wallet to load the frozen criteria.")); }); }, [params]);
  function addRef(index: number) { setRefs((all) => ({ ...all, [index]: [...(all[index] || []), { criterion: index, kind: "VERSIONED_SOURCE", url: "", note: "" }] })); }
  function updateRef(index: number, refIndex: number, patch: Partial<EvidenceRef>) { setRefs((all) => ({ ...all, [index]: (all[index] || []).map((ref, i) => i === refIndex ? { ...ref, ...patch } : ref) })); }
  function removeRef(index: number, refIndex: number) { setRefs((all) => ({ ...all, [index]: (all[index] || []).filter((_, i) => i !== refIndex) })); }
  const payload = item?.criteria.flatMap((c) => refs[c.index] || []) || [];
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!item || item.status !== "ACTIVE") { setError("Only an ACTIVE engagement can receive an attempt."); return; } const evidenceError = validateEvidenceRefs(item.criteria, payload); if (evidenceError) { setError(evidenceError); return; } try { const accounts = await requestAccounts(); const tx = await writeContract("evaluate_attempt", [engagementId, JSON.stringify(payload)], accounts[0], window.ethereum!); setHash(tx); } catch (e) { setError(e instanceof Error ? e.message : "The evidence transaction failed or was rejected."); } }
  async function confirmCanonicalAttempt() { try { const accounts = await requestAccounts(); const [engagement, attempts] = await Promise.all([readContract<Engagement>("get_engagement", [engagementId], window.ethereum, accounts[0]), readContract<Array<{ number: number; result: string }>>("get_attempts", [engagementId], window.ethereum, accounts[0])]); const latest = attempts?.[attempts.length - 1]; setItem(engagement); setCanonical(latest ? `Canonical readback: attempt ${latest.number} · product result ${latest.result} · engagement ${engagement.status}.` : "Finalized transaction had no canonical attempt readback."); } catch (e) { setError(e instanceof Error ? e.message : "Finalized, but canonical readback failed."); } }
  if (!item) return <section className="doc"><div className="eyebrow">Engagement {engagementId || "…"}</div><h1>Prove each requirement.</h1><p className={error ? "error" : "muted"}>{error || "Reading frozen criteria from Studionet…"}</p></section>;
  return <section className="doc"><div className="eyebrow">Engagement {item.id} · public evidence</div><h1>Prove each requirement.</h1><p className="muted">Attach bounded public evidence to the exact criterion it proves. Validators inspect only these URLs; notes are provenance, not proof.</p>{hash && <TransactionNotice hash={hash} label="Evaluate evidence attempt" onFinalized={confirmCanonicalAttempt} />}{canonical && <p className="success">{canonical}</p>}<form className="form" onSubmit={submit}><div className="criteria">{item.criteria.map((criterion) => <article className="criterion" key={criterion.index}><div className="row"><h3>Criterion {criterion.index + 1}</h3><span className="pill">{criterion.required ? "Required" : "Optional"}</span></div><p>{criterion.text}</p>{(refs[criterion.index] || []).map((ref, refIndex) => <div className="evidenceRow" key={refIndex}><label className="field">Source kind<select value={ref.kind} onChange={(e) => updateRef(criterion.index, refIndex, { kind: e.target.value as EvidenceKind })}>{kinds.map((kind) => <option key={kind}>{kind}</option>)}</select></label><label className="field">HTTPS URL<input value={ref.url} onChange={(e) => updateRef(criterion.index, refIndex, { url: e.target.value })} placeholder="https://…" /></label><label className="field">Short note (optional)<input value={ref.note || ""} onChange={(e) => updateRef(criterion.index, refIndex, { note: e.target.value })} maxLength={240} placeholder="What this source may demonstrate" /></label><button type="button" className="textButton" onClick={() => removeRef(criterion.index, refIndex)}>Remove</button></div>)}{(refs[criterion.index] || []).length < 2 && <button type="button" className="secondary" onClick={() => addRef(criterion.index)}>Attach evidence to this criterion</button>}</article>)}</div><div className="panel"><h3>Exact payload preview</h3><p className="muted">This JSON is the payload that will be signed. It is bounded to the selected criteria and public HTTPS URLs.</p><pre className="preview">{JSON.stringify(payload, null, 2)}</pre></div>{error && <p className="error">{error}</p>}<button type="submit">Sign evidence submission</button></form></section>;
}
