"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { readContract } from "@/lib/genlayer";
import { requestAccounts } from "@/lib/wallet";
import type { Engagement } from "@/lib/types";
import { WalletPanel } from "@/components/WalletPanel";
const statusText: Record<string, string> = { PROPOSED: "Awaiting acceptance", ACTIVE: "In progress", COMPLETED: "Completed", DECLINED: "Declined", CANCELLED: "Cancelled", EXPIRED: "Expired" };
export default function WorkPage() {
  const [account, setAccount] = useState(""); const [items, setItems] = useState<Engagement[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); setError(""); try { const accounts = await requestAccounts(); const ids = await readContract<string[]>("get_wallet_engagements", [accounts[0]], window.ethereum, accounts[0]); const engagements = await Promise.all((ids || []).map((id) => readContract<Engagement>("get_engagement", [String(id)], window.ethereum, accounts[0]))); setAccount(accounts[0]); setItems(engagements); } catch (e) { setError(e instanceof Error ? e.message : "Connect a wallet to load canonical engagements."); } finally { setLoading(false); } }
  useEffect(() => { if (window.ethereum) { window.ethereum.request({ method: "eth_accounts" }).then((ids) => { if (Array.isArray(ids) && ids[0]) load(); }).catch(() => undefined); } }, []);
  return <><WalletPanel /><div className="workspace"><section className="doc"><div className="eyebrow">Work desk</div><h1>Your engagements</h1><p className="muted">Every card below is reconstructed from the wallet-scoped contract index and canonical engagement reads.</p><div className="row"><button onClick={load}>{loading ? "Loading…" : account ? "Refresh work" : "Connect and load"}</button><Link className="button secondary" href="/work/new">New engagement</Link></div>{error && <p className="error">{error}</p>}<div className="cardList">{!loading && items.length === 0 && <div className="panel"><strong>No canonical engagements found.</strong><p className="muted">Create a proposal or connect the wallet that is a requester or designated performer.</p></div>}{items.map((item) => <Link className="engagementCard" key={item.id} href={`/work/${item.id}`}><div className="row"><span className="pill">{statusText[item.status] || item.status}</span><span className="muted">#{item.id}</span></div><h2>{item.title}</h2><p className="muted">{item.summary}</p><div className="meta"><span>{item.criteria?.length || 0} frozen criteria</span><span>{item.requester?.toLowerCase() === account.toLowerCase() ? "Requester" : "Performer"}</span></div></Link>)}</div></section><aside className="panel"><h3>One milestone at a time</h3><p className="muted">Accordant keeps the agreement small enough to inspect: one frozen delivery milestone, bounded criterion evidence, and an append-only attempt ledger.</p></aside></div></>;
}
