"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { readContract, writeContract } from "@/lib/genlayer";
import { requestAccounts } from "@/lib/wallet";
import type { Engagement } from "@/lib/types";
import { TransactionNotice } from "@/components/TransactionNotice";
import { StatusPill } from "@/components/StatusPill";
export default function EngagementPage({ params }: { params: Promise<{ engagementId: string }> }) {
  const [engagementId, setEngagementId] = useState(""); const [item, setItem] = useState<Engagement | null>(null); const [account, setAccount] = useState(""); const [hash, setHash] = useState(""); const [error, setError] = useState("");
  async function load(id: string) { try { const accounts = await requestAccounts(); setAccount(accounts[0]); setItem(await readContract<Engagement>("get_engagement", [id], window.ethereum, accounts[0])); } catch (e) { setError(e instanceof Error ? e.message : "Could not load this engagement."); } }
  useEffect(() => { params.then(({ engagementId: id }) => { setEngagementId(id); load(id); }); }, [params]);
  async function action(name: string) { try { const accounts = await requestAccounts(); const tx = await writeContract(name, [engagementId], accounts[0], window.ethereum!); setHash(tx); } catch (e) { setError(e instanceof Error ? e.message : "Transaction failed or was rejected."); } }
  if (!item) return <section className="doc"><div className="eyebrow">Engagement {engagementId || "…"}</div><h1>Milestone workspace</h1>{error ? <p className="error">{error}</p> : <p className="muted">Reading canonical terms from Studionet…</p>}</section>;
  const requester = item.requester.toLowerCase() === account.toLowerCase(); const performer = item.performer.toLowerCase() === account.toLowerCase();
  return <><div className="workspace"><section className="doc"><div className="eyebrow">Engagement {item.id}</div><div className="titleRow"><h1>{item.title}</h1><StatusPill>{item.status}</StatusPill></div><p className="lede">{item.summary}</p><div className="panel digest"><span className="muted">Frozen terms digest</span><code>{item.terms_digest}</code></div><div className="criteria">{item.criteria.map((criterion) => <article className="criterion" key={criterion.index}><div className="row"><h3>Criterion {criterion.index + 1}</h3><span className="pill">{criterion.required ? "Required" : "Optional"}</span></div><p>{criterion.text}</p></article>)}</div><div className="cta" style={{ marginTop: 20 }}>{performer && item.status === "PROPOSED" && <><button onClick={() => action("accept_engagement")}>Accept terms</button><button className="secondary" onClick={() => action("decline_engagement")}>Decline</button></>}{requester && item.status === "PROPOSED" && <button className="secondary" onClick={() => action("cancel_proposal")}>Cancel proposal</button>}{item.status === "ACTIVE" && performer && <Link className="button" href={`/work/${item.id}/submit`}>Submit evidence</Link>}{(item.status === "PROPOSED" || item.status === "ACTIVE") && <button className="secondary" onClick={() => action("close_expired")}>Close after deadline</button>}<Link className="button secondary" href={`/work/${item.id}/history`}>Attempt history</Link></div>{hash && <TransactionNotice hash={hash} label="Engagement action" onFinalized={() => load(engagementId)} />}{error && <p className="error">{error}</p>}</section><aside className="panel context"><h3>Agreement context</h3><p><strong>Requester</strong><br /><span className="mono">{item.requester}</span></p><p><strong>Performer</strong><br /><span className="mono">{item.performer}</span></p><p><strong>Proposal closes</strong><br />{new Date(item.proposal_deadline * 1000).toLocaleString()}</p><p><strong>Delivery closes</strong><br />{new Date(item.delivery_deadline * 1000).toLocaleString()}</p><p><strong>Attempts</strong><br />{item.attempt_count} · latest {item.latest_result || "none"}</p></aside></div></>;
}
