"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { readContract } from "@/lib/genlayer";
import type { Attempt, AttemptPage, Engagement } from "@/lib/types";
import { StatusPill } from "@/components/StatusPill";

type Decision = { index: number; status: "MET" | "NOT_MET" | "UNVERIFIABLE"; explanation: string };

export default function Review({ params }: { params: Promise<{ engagementId: string; attemptId: string }> }) {
  const [ids, setIds] = useState({ engagementId: "", attemptId: "" }); const [item, setItem] = useState<Engagement | null>(null); const [attempt, setAttempt] = useState<Attempt | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; params.then(async ({ engagementId, attemptId }) => { if (!active) return; setIds({ engagementId, attemptId }); try { const engagement = await readContract<Engagement>("get_engagement", [engagementId]); let offset = 0; let found: Attempt | null = null; do { const attempts = await readContract<AttemptPage>("get_attempts", [engagementId, offset, 20]); found = (attempts.items || []).find((entry) => String(entry.number) === attemptId) || null; offset = attempts.next_offset; } while (!found && offset); if (active) { setItem(engagement); setAttempt(found); if (!found) setError("That attempt is not present in the canonical ledger."); } } catch (e) { if (active) setError(e instanceof Error ? e.message : "Could not load the canonical attempt."); } }); return () => { active = false; }; }, [params]);
  if (error || !item || !attempt) return <section className="doc"><div className="eyebrow">Attempt {ids.attemptId}</div><h1>Attempt review</h1><p className={error ? "error" : "muted"}>{error || "Reading the append-only attempt ledger…"}</p></section>;
  let decisions: Decision[] = []; try { const parsed: unknown = JSON.parse(attempt.decisions_json); if (!Array.isArray(parsed) || parsed.some((entry) => !entry || typeof entry !== "object")) throw new Error("not an array"); decisions = parsed as Decision[]; } catch { return <section className="doc"><div className="eyebrow">Engagement {ids.engagementId} · Attempt {attempt.number}</div><h1>Attempt review</h1><p className="error">Stored decision vector is malformed. The result is not trusted.</p></section>; }
  const decisionFor = (index: number) => decisions.find((entry) => entry.index === index);
  return <div className="workspace"><section className="doc"><div className="eyebrow">Review matrix · engagement {ids.engagementId} · attempt {attempt.number}</div><div className="titleRow"><div><h1>What the evidence proved.</h1><p className="lede">A canonical validator decision for each frozen criterion, preserved with the submission that produced it.</p></div><StatusPill>{attempt.result}</StatusPill></div><div className="outcomeBanner"><div><span className="eyebrow">Product result</span><strong>{attempt.result === "ACCEPTED" ? "Acceptance recorded" : attempt.result === "REVISION_REQUIRED" ? "Revision requested" : "More certainty needed"}</strong></div><span className="mono">Attempt {attempt.number} · {new Date(attempt.submitted_at * 1000).toLocaleString()}</span></div><div className="criteria reviewMatrix">{item.criteria.map((criterion) => { const decision = decisionFor(criterion.index); const status = decision?.status || "UNVERIFIABLE"; return <article className="criterion" key={criterion.index}><div className="row criterionHead"><div><span className="eyebrow">Criterion {String(criterion.index + 1).padStart(2, "0")}</span><h3>{criterion.text}</h3></div><span className={`decision ${status.toLowerCase()}`}>{status}</span></div><div className="decisionExplanation"><span className="muted">{criterion.required ? "Required for acceptance" : "Supporting criterion"}</span><p>{decision?.explanation || "No explanation stored; this criterion is treated as unverifiable."}</p></div></article>; })}</div><details className="technicalDetails"><summary>Integrity details</summary><div className="digest"><span className="muted">Submission digest</span><code>{attempt.submission_digest}</code></div><h3>Evidence payload</h3><pre className="preview">{attempt.evidence_json}</pre><h3>Stored decision vector</h3><pre className="preview">{attempt.decisions_json}</pre></details><div className="row"><Link className="button secondary" href={`/work/${ids.engagementId}/history`}>All attempts</Link>{item.status === "ACTIVE" && <Link className="button lemon" href={`/work/${ids.engagementId}/submit`}>Submit another attempt</Link>}</div></section><aside className="panel context"><div className="eyebrow">Decision legend</div><h3>Read the matrix</h3><p><strong className="successText">MET</strong><br /><span className="muted">Evidence substantively demonstrates the criterion.</span></p><p><strong className="revisionText">NOT_MET</strong><br /><span className="muted">Evidence clearly shows the criterion is not satisfied.</span></p><p><strong className="inconclusiveText">UNVERIFIABLE</strong><br /><span className="muted">Evidence is missing, unavailable, ambiguous, or insufficient.</span></p><div className="railMarker"><span>Engagement state</span><strong>{item.status}</strong></div></aside></div>;
}
