"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { readContract } from "@/lib/genlayer";
import { requestAccounts } from "@/lib/wallet";
import type { Attempt, Engagement } from "@/lib/types";
import { StatusPill } from "@/components/StatusPill";
export default function Review({ params }: { params: Promise<{ engagementId: string; attemptId: string }> }) {
  const [ids, setIds] = useState({ engagementId: "", attemptId: "" }); const [item, setItem] = useState<Engagement | null>(null); const [attempt, setAttempt] = useState<Attempt | null>(null); const [error, setError] = useState("");
  useEffect(() => { params.then(({ engagementId, attemptId }) => { setIds({ engagementId, attemptId }); requestAccounts().then(async (a) => { const [engagement, attempts] = await Promise.all([readContract<Engagement>("get_engagement", [engagementId], window.ethereum, a[0]), readContract<Attempt[]>("get_attempts", [engagementId], window.ethereum, a[0])]); setItem(engagement); setAttempt((attempts || []).find((entry) => String(entry.number) === attemptId) || null); }).catch((e) => setError(e instanceof Error ? e.message : "Could not load the canonical attempt.")); }); }, [params]);
  if (error || !item || !attempt) return <section className="doc"><div className="eyebrow">Attempt {ids.attemptId}</div><h1>Attempt review</h1><p className={error ? "error" : "muted"}>{error || "Reading the append-only attempt ledger…"}</p></section>;
  let decisions: Array<{ index: number; status: string; explanation: string }> = []; try { decisions = JSON.parse(attempt.decisions_json); } catch { setError("Stored decision vector is malformed."); }
  return <section className="doc"><div className="eyebrow">Engagement {ids.engagementId} · Attempt {attempt.number}</div><h1>Attempt review</h1><div className="row"><StatusPill>{attempt.result}</StatusPill><StatusPill>CANONICAL RESULT</StatusPill></div><p className="muted">This is the product outcome stored by the contract. GenLayer transaction lifecycle is displayed separately on the submitting transaction.</p><div className="criteria">{item.criteria.map((criterion) => { const decision = decisions.find((entry) => entry.index === criterion.index); return <article className="criterion" key={criterion.index}><div className="row"><h3>Criterion {criterion.index + 1}</h3><span className="pill">{criterion.required ? "Required" : "Optional"}</span><span className={`decision ${decision?.status?.toLowerCase()}`}>{decision?.status || "UNVERIFIABLE"}</span></div><p>{criterion.text}</p><p className="muted">{decision?.explanation || "No explanation stored."}</p></article>; })}</div><div className="panel"><h3>Submission binding</h3><p className="mono">{attempt.submission_digest}</p><pre className="preview">{attempt.evidence_json}</pre></div><div className="row"><Link className="button secondary" href={`/work/${ids.engagementId}/history`}>All attempts</Link>{item.status === "ACTIVE" && <Link className="button" href={`/work/${ids.engagementId}/submit`}>Submit another attempt</Link>}</div></section>;
}
